apiVersion: batch/v1
kind: Job
metadata:
  name: redis-init
  namespace: betteruptime
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: redis-init
        image: aabhii/betteruptime-init:amd64-latest
        workingDir: /app/packages/store
        command:
          - sh
          - -c
          - "/app/wait-for-redis.sh redis 6379 && bun run redis-seed"
        env:
          - name: REDIS_URL
            valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_URL
      initContainers:
      - name: wait-for-redis
        image: aabhii/betteruptime-init:amd64-latest
        command: ["/app/wait-for-redis.sh", "redis", "6379"]